# Generated by Django 5.0.1 on 2026-01-16 11:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PilotApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                (
                    "fleet_size",
                    models.CharField(
                        choices=[
                            ("1-5", "1-5 riders"),
                            ("6-15", "6-15 riders"),
                            ("16-50", "16-50 riders"),
                            ("51-100", "51-100 riders"),
                            ("100+", "100+ riders"),
                        ],
                        max_length=10,
                    ),
                ),
                ("challenges", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Contacted"),
                            ("onboarding", "Onboarding"),
                            ("active", "Active Pilot"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="demo_page", max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pilot Application",
                "verbose_name_plural": "Pilot Applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
