# Generated by Django 5.0.1 on 2025-12-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("riders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_order_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("delivery_address", models.TextField()),
                (
                    "delivery_address_normalized",
                    models.TextField(blank=True, null=True),
                ),
                ("delivery_city", models.CharField(default="Accra", max_length=100)),
                (
                    "delivery_landmark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("geocoding_confidence", models.FloatField(blank=True, null=True)),
                ("delivery_window_start", models.DateTimeField(blank=True, null=True)),
                ("delivery_window_end", models.DateTimeField(blank=True, null=True)),
                (
                    "preferred_vehicle",
                    models.CharField(
                        choices=[
                            ("motorbike", "Motorbike"),
                            ("van", "Van"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("package_description", models.TextField(blank=True, null=True)),
                ("package_weight_kg", models.FloatField(default=1.0)),
                ("package_size", models.CharField(default="medium", max_length=50)),
                ("is_fragile", models.BooleanField(default=False)),
                ("is_cod", models.BooleanField(default=False)),
                ("cod_amount", models.FloatField(default=0.0)),
                ("cod_collected", models.FloatField(blank=True, null=True)),
                ("cod_collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_notes", models.TextField(blank=True, null=True)),
                ("route_stop_sequence", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("delivery_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="riders.rider",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
