# Generated by Django 5.0.1 on 2025-12-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="routes.route",
            ),
        ),
    ]
