# Generated by Django 5.0.1 on 2025-12-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("orders", "0001_initial"),
        ("riders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("route_date", models.DateField(db_index=True)),
                ("vehicle_type", models.CharField(default="motorbike", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("optimized", "Optimized"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_stops", models.IntegerField(default=0)),
                ("total_distance_km", models.FloatField(default=0.0)),
                ("total_duration_minutes", models.FloatField(default=0.0)),
                ("estimated_fuel_cost", models.FloatField(default=0.0)),
                ("naive_distance_km", models.FloatField(blank=True, null=True)),
                ("naive_duration_minutes", models.FloatField(blank=True, null=True)),
                ("distance_saved_km", models.FloatField(blank=True, null=True)),
                ("distance_saved_percent", models.FloatField(blank=True, null=True)),
                ("time_saved_minutes", models.FloatField(blank=True, null=True)),
                ("fuel_cost_saved", models.FloatField(blank=True, null=True)),
                ("route_geometry", models.JSONField(blank=True, null=True)),
                ("optimized_stop_order", models.JSONField(blank=True, null=True)),
                ("start_latitude", models.FloatField(blank=True, null=True)),
                ("start_longitude", models.FloatField(blank=True, null=True)),
                (
                    "start_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("end_latitude", models.FloatField(blank=True, null=True)),
                ("end_longitude", models.FloatField(blank=True, null=True)),
                (
                    "end_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_cod_expected", models.FloatField(default=0.0)),
                ("total_cod_collected", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="riders.rider",
                    ),
                ),
            ],
            options={
                "db_table": "routes",
                "ordering": ["-route_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.TextField(blank=True, null=True)),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("distance_from_previous_km", models.FloatField(blank=True, null=True)),
                (
                    "duration_from_previous_minutes",
                    models.FloatField(blank=True, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="orders.order",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_stops",
                "ordering": ["sequence"],
                "unique_together": {("route", "order")},
            },
        ),
    ]
