# Generated by Django 5.0.1 on 2025-12-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("riders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("photo_path", models.CharField(blank=True, max_length=500, null=True)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_verified", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recipient_signature", models.TextField(blank=True, null=True)),
                ("delivery_latitude", models.FloatField(blank=True, null=True)),
                ("delivery_longitude", models.FloatField(blank=True, null=True)),
                ("cod_amount_collected", models.FloatField(default=0.0)),
                (
                    "cod_payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_of_delivery",
                        to="orders.order",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proof_of_deliveries",
                        to="riders.rider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proof of Delivery",
                "verbose_name_plural": "Proofs of Delivery",
                "db_table": "proof_of_delivery",
            },
        ),
    ]
