# Generated by Django 5.0.1 on 2025-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("hashed_password", models.CharField(max_length=255)),
                ("business_name", models.CharField(max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("ecommerce", "E-Commerce"),
                            ("pharmacy", "Pharmacy"),
                            ("supermarket", "Supermarket"),
                            ("sme", "SME"),
                            ("courier", "Courier"),
                            ("other", "Other"),
                        ],
                        default="sme",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("city", models.CharField(default="Accra", max_length=100)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(default="trial", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "merchants",
                "ordering": ["-created_at"],
            },
        ),
    ]
